import components from "../components";
import { motion } from "framer-motion";
import { Suspense, useMemo } from "react";
import { IElement } from "../types/routes";
import Placeholder from "@/components/placeholder";
import { Skeleton } from "@/components/ui/skeleton";
import ErrorElement from "../components/ErrorElement";
import ContentSection from "@/components/layout/content-section";
import { Await, useLoaderData, useLocation } from "react-router";
import { cn } from "@/lib/utils";

const RenderComponent = ({
  data,
  element,
}: {
  data: Record<string, any>;
  element: IElement;
}) => {
  if (!element.element) return null;
  const Component = components[element.element];
  if (element.api)
    return (
      <Suspense fallback={<Skeleton className="h-full min-h-30" />}>
        <Await
          resolve={data[element.id]}
          errorElement={<ErrorElement {...element} />}
        >
          {(dataProps) => <Component {...element.props} {...dataProps} />}
        </Await>
      </Suspense>
    );
  return <Component {...element.props} />;
};

export default function AutoGeneratedPage() {
  const data = useLoaderData();

  const renderElements = useMemo(() => {
    return data.currentRoute.elements?.map((element: IElement) => {
      return (
        <div key={element.id} className={cn("col-span-12", `${element.size}`)}>
          <RenderComponent element={element} data={data} />
        </div>
      );
    });
  }, [data]);

  return (
    <motion.div
      className="flex flex-col gap-3"
      animate={{ translateX: 0 }}
      initial={{ translateX: -30 }}
    >
      <ContentSection
        title={data.currentRoute.title}
        description={`explore the ${data.currentRoute.title} with ease`}
      />
      {!data.currentRoute?.elements.length && <Placeholder />}
      <div className="grid grid-cols-12 gap-3 h-full">{renderElements}</div>
    </motion.div>
  );
}
